### ISSUE TITLE
how to make this work with new gstreamer va plugin?

### ISSUE THREAD

**Issue by flang3** [flathub/com.obsproject.Studio.Plugin.GStreamerVaapi#17]
With the flatpak versions of obs an gstreamervaapi plugin i am only seeing the legacy option.

My `flatpak list | grep obs` output:

```
OBS Studio      com.obsproject.Studio   29.1.3  stable  system
OBS VkCapture Plugin    com.obsproject.Studio.Plugin.OBSVkCapture       1.4.5   stable  system
```
and `flatpak list | grep -i gstreamer` output:

```
GStreamer VA-API Plugin com.obsproject.Studio.Plugin.GStreamerVaapi     0.4.0   stable  system
GStreamer Plugin        com.obsproject.Studio.Plugin.Gstreamer  0.4.0   stable  system
gstreamer-vaapi org.freedesktop.Platform.GStreamer.gstreamer-vaapi              21.08   system
gstreamer-vaapi org.freedesktop.Platform.GStreamer.gstreamer-vaapi              22.08   system
gstreamer-vaapi org.freedesktop.Platform.GStreamer.gstreamer-vaapi              23.08   system
```

![image](https://github.com/flathub/com.obsproject.Studio.Plugin.GStreamerVaapi/assets/76410865/5c17b975-55ad-4569-a971-07a832b95fdb)

As you can see com.obsproject.Studio.Plugin.Gstreamer ist also picked up.

My `gst-inspect-1.0 va` output:

```
Plugin Details:
  Name                     va
  Description              VA-API codecs plugin
  Filename                 /lib/x86_64-linux-gnu/gstreamer-1.0/libgstva.so
  Version                  1.22.0
  License                  LGPL
  Source module            gst-plugins-bad
  Documentation            https://gstreamer.freedesktop.org/documentation/va/
  Source release date      2023-01-23
  Binary package           GStreamer Bad Plugins (Debian)
  Origin URL               https://tracker.debian.org/pkg/gst-plugins-bad1.0

  vaav1dec: VA-API AV1 Decoder
  vacompositor: VA-API Video Compositor
  vadeinterlace: VA-API Deinterlacer
  vah264dec: VA-API H.264 Decoder
  vah264enc: VA-API H.264 Encoder
  vah265dec: VA-API H.265 Decoder
  vah265enc: VA-API H.265 Encoder
  vajpegdec: VA-API JPEG Decoder
  vapostproc: VA-API Video Postprocessor
  vavp9dec: VA-API VP9 Decoder

  10 features:
  +-- 10 elements
```

I am on  debian bookworm. The native obs-studio picks up the new encoder. But i would rather use the flatpak version.

Does ist maybe have something to do with some env variables? Like `GST_PLUGIN_SYSTEM_PATH` for gstreamer?

**Comment by flang3** [comment]
I got a little futher. Attaching to the flatpak container via `flatpak run --command=bash com.obsproject.Studio` resulted in

```
$ gst-inspect-1.0 va
Plugin Details:
  Name                     va
  Description              VA-API codecs plugin
  Filename                 /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstva.so
  Version                  1.20.7
  License                  LGPL
  Source module            gst-plugins-bad
  Source release date      2023-07-26
  Binary package           GStreamer Bad Plug-ins source release
  Origin URL               freedesktop-sdk

  vaav1dec: VA-API AV1 Decoder
  vadeinterlace: VA-API Deinterlacer
  vah264dec: VA-API H.264 Decoder
  vah265dec: VA-API H.265 Decoder
  vapostproc: VA-API Video Postprocessor
  vavp9dec: VA-API VP9 Decoder
```
I guess all gstreamer encoders of the freedesktop sdk are deactivated?

**Comment by daveth91** [comment]
The encoders are in the vaapi plugin provided by org.freedesktop.Platform.GStreamer.gstreamer-vaapi:

```
[📦 com.obsproject.Studio ~]$ gst-inspect-1.0 vaapi
Plugin Details:
  Name                     vaapi
  Description              VA-API based elements
  Filename                 /usr/lib/extensions/gstreamer-1.0/gstreamer-vaapi/libgstvaapi.so
  Version                  1.20.7
  License                  LGPL
  Source module            gstreamer-vaapi
  Source release date      2023-07-26
  Binary package           gstreamer-vaapi
  Origin URL               Unknown package origin

  vaapiav1dec: VA-API AV1 decoder
  vaapidecodebin: VA-API Decode Bin
  vaapih264dec: VA-API H264 decoder
  vaapih264enc: VA-API H264 encoder
  vaapih265dec: VA-API H265 decoder
  vaapih265enc: VA-API H265 encoder
  vaapijpegdec: VA-API JPEG decoder
  vaapimpeg2dec: VA-API MPEG2 decoder
  vaapipostproc: VA-API video postprocessing
  vaapisink: VA-API sink
  vaapivc1dec: VA-API VC1 decoder
  vaapivp9dec: VA-API VP9 decoder

  12 features:
  +-- 12 elements
```

Don't know why it's called (Legacy) in OBS settings though.

**Comment by flang3** [comment]
As explained by @fzwoch here https://github.com/fzwoch/obs-vaapi/issues/19#issuecomment-1784069436 the vaapi is old and (soon?) to be deprecated?

**Comment by fzwoch** [comment]
> I got a little futher. Attaching to the flatpak container via `flatpak run --command=bash com.obsproject.Studio` resulted in
> 
> ```
> $ gst-inspect-1.0 va
> Plugin Details:
>   Name                     va
>   Description              VA-API codecs plugin
>   Filename                 /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstva.so
>   Version                  1.20.7
>   License                  LGPL
>   Source module            gst-plugins-bad
>   Source release date      2023-07-26
>   Binary package           GStreamer Bad Plug-ins source release
>   Origin URL               freedesktop-sdk
> 
>   vaav1dec: VA-API AV1 Decoder
>   vadeinterlace: VA-API Deinterlacer
>   vah264dec: VA-API H.264 Decoder
>   vah265dec: VA-API H.265 Decoder
>   vapostproc: VA-API Video Postprocessor
>   vavp9dec: VA-API VP9 Decoder
> ```
> 
> I guess all gstreamer encoders of the freedesktop sdk are deactivated?

Iirc the encoders were added in GStreamer 1.22.

**Comment by RushingAlien** [comment]
@Pearf1337 , OBS flatpak is built with the org.kde.Platform 6.5 branch, which uses the org.freedesktop.Platform 22.08 branch

The VA encoders are only added in the org.freedesktop.Platform 23.08 branch, OBS flatpak will need to be built with org.kde.Platform 6.6 branch to get the VA encoders
